const aboutData = [
  {
    idx: 1,
    category: "Design",
    categorySlug: "design",
    title: "Design Esportivo",
    slug: "design-esportivo",
    description:
      "Todo o estilo que só o design italiano pode proporcionar. Surpreenda a si mesmo e a todos com o novo Cronos.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-design-esportivo.jpg",
  },
  {
    idx: 2,
    category: "Design",
    categorySlug: "design",
    title: "Rodas de Liga-leve",
    slug: "rodas-liga-leve",
    description:
      "Conduza com elegância e chame a atenção por onde passar através das rodas de liga-leve com desenho dinâmico e acabamento diamantado.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-design-rodas.jpg",
  },
  {
    idx: 3,
    category: "Design",
    categorySlug: "design",
    slug: "farois-led",
    title: "Faróis com <br />Assinatura em LED",
    description:
      "O brilho no olhar do Fiat Cronos fica por conta dos faróis com assinatura em LED, que dão um toque de esportividade e modernidade ao visual do carro.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-design-farois-led.jpg",
  },
  {
    idx: 1,
    category: "Tecnologia",
    categorySlug: "tecnologia",
    slug: "central-multimidia",
    title: 'Central Multimídia UConnect 7"',
    description:
      "Conecte-se em seu smartphone via Android Auto ou Apple CarPlay para dirigir com seus apps favoritos espelhados em uma tela de 7” polegadas.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-tecnologia-central-multi.jpg",
  },
  {
    idx: 2,
    category: "Tecnologia",
    categorySlug: "tecnologia",
    slug: "keyless-entry-n-go",
    title: "Keyless Entry N'Go",
    description:
      "Seu carro reconhecerá a presença da chave próximo e dentro dele, então é só entrar e dar a partida. Prático demais, não é mesmo?",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-tecnologia-keyless.jpg",
  },
  {
    idx: 3,
    category: "Tecnologia",
    categorySlug: "tecnologia",
    slug: "volante-multifuncional",
    title: "Volante Multifuncional",
    description:
      "Defina a velocidade do piloto automático e troque as marchas através das alavancas de troca de marchas (paddle shifters)",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-tecnologia-volante.jpg",
  },
  // {
  //   idx: 4,
  //   category: "Tecnologia",
  //   categorySlug: "tecnologia",
  //   slug: "ar-condicionado-digital",
  //   title: "Ar-Condicionado Digital",
  //   description:
  //     "Que tal ter o controle do clima na palma da sua mão? Escolha a climatização de acordo com a sua preferência. Com o novo ar-condicionado automático digital, você desfruta de uma seleção gradual de temperatura.",
  //   link: "",
  //   labelLink: "",
  //   image: "/assets/images/about/img-tecnologia-volante.jpg",
  // },
  {
    idx: 1,
    category: "Performance",
    categorySlug: "performance",
    slug: "novo-cambio-automatico-cvt",
    title: "Novo Câmbio <br />Automático CVT",
    description:
      "Mais conforto e economia! Aliado ao motor Firefly 1.3, descubra que é possível ter performance e autonomia ao mesmo tempo. Nada mal, não?",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-performance-cvt.jpg",
  },
  {
    idx: 2,
    category: "Performance",
    categorySlug: "performance",
    slug: "moto-firefly",
    title: "Motor Firefly 1.0",
    description:
      "Mais eficiência em qualquer caminho. A grande força do Motor Firefly 1.0 transforma deslocamentos do dia a dia em grandes jornadas.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-performance-motor.jpg",
  },
  {
    idx: 3,
    category: "Performance",
    categorySlug: "performance",
    slug: "direcao-eletrica-progressiva",
    title: "Direção Elétrica <br />Progressiva",
    description:
      "Além da economia de combustível, a direção elétrica progressiva também personaliza o nível de resistência do volante acompanhando a velocidade do carro.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-performance-direcao.jpg",
  },
  {
    idx: 1,
    category: "Segurança",
    categorySlug: "seguranca",
    slug: "hill-holder",
    title: "Hill Holder",
    description:
      "Mais conforto para sua direção com o auxiliar de partida em ladeiras, assim as saídas continuam suaves mesmo nos terrenos mais acentuados.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-seguranca-hill-holder.jpg",
  },
  {
    idx: 2,
    category: "Segurança",
    categorySlug: "seguranca",
    slug: "camera-re",
    title: "Câmera de Ré com <br class=\"desktop\" />Linhas Dinâmicas",
    description:
      "Facilite suas manobras, sem precisar olhar para trás. Ao engatar a marcha ré, a câmera transmite os obstáculos no caminho direto na central multimídia.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-seguranca-camera-re.jpg",
  },
  {
    idx: 3,
    category: "Segurança",
    categorySlug: "seguranca",
    slug: "controle-tracao-estabilidade",
    title: "Controle de Tração <br class=\"desktop\" />e Estabilidade",
    description:
      "O Fiat Cronos estabiliza a carroceria automaticamente nas curvas mais difíceis. É mais segurança para sua direção e seu passeio.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-seguranca-controle-tracao.jpg",
  },
  {
    idx: 1,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "farol-neblina",
    title: "Farol de Neblina",
    description:
      "Com a função de aprimorar a iluminação em caso de neblina, tempestade e chuviscos intensos, também destaca os dispositivos refletivos que estão na rua, guiando você do jeito mais seguro no seu trajeto.",
    link: "https://www.fiat.com.br",
    labelLink: "Eu quero",
    image: "/assets/images/about/img-acessorios-neblina.jpg",
  },
  {
    idx: 2,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "tapete-porta-malas",
    title: "Tapete do Porta-Malas",
    description:
      "Protege o forro do porta-malas e ainda garante mais estabilidade e aderência aos itens colocados no bagageiro.",
    link: "https://www.fiat.com.br",
    labelLink: "Eu quero",
    image: "/assets/images/about/img-acessorios-tapete.jpg",
  },
  {
    idx: 3,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "tapete-borracha",
    title: "Tapete de Borracha",
    description:
      "Proteção para o carpete do seu Fiat Cronos. Mais espessos e resistentes, também ajudam a compor o interior do carro, além de possuírem os mesmos elementos gráficos do veículo.",
    link: "https://www.fiat.com.br",
    labelLink: "Eu quero",
    image: "/assets/images/about/img-acessorios-tapete-borracha.jpg",
  },
  {
    idx: 4,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "friso-lateral-pintado",
    title: "Frisos Laterais",
    description:
      "Cuidado redobrado com a lateral do seu Fiat Cronos. Os frisos laterais protegem as portas de pequenos danos e ainda dão um visual invocado ao carro.",
    link: "https://www.fiat.com.br",
    labelLink: "Eu quero",
    image: "/assets/images/about/img-acessorios-friso.jpg",
  },
  {
    idx: 5,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "engate-reboque",
    title: "Reboque Removível",
    description:
      "Remova a lança quando não estiver em uso, sem nenhuma furação adicional e mantendo a garantia do serviço com o engate reboque Mopar.",
    link: "https://www.fiat.com.br",
    labelLink: "Eu quero",
    image: "/assets/images/about/img-acessorios-engate.jpg",
  },
  {
    idx: 1,
    category: "Serviços",
    categorySlug: "servicos",
    slug: "cuidado-fiat-cronos-merece",
    title: "O Cuidado que o seu <br class=\"desktop\" />Fiat Cronos Merece",
    description:
      "O seu Fiat Cronos pode ter até 5 anos de garantia além das Revisões sob medida com descontos e preços fixos. Conheça os pacotes de Serviços FIAT Mopar.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-servicos-cuidade-fiat.jpg",
  },
  {
    idx: 2,
    category: "Serviços",
    categorySlug: "servicos",
    slug: "garantia-adicional-fiat",
    title: "Garantia <br class=\"desktop\" />Adicional Fiat",
    description:
      "Com planos a partir de R$ 2 por dia, você pode estender a garantia do seu Fiat Cronos por mais 1 ou 2 anos, além dos 3 anos de fábrica.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-servicos-garantia-fiat.jpg",
  },
  {
    idx: 3,
    category: "Serviços",
    categorySlug: "servicos",
    slug: "revisoes-sob-medida",
    title: "Revisões Sob <br class=\"desktop\" />Medida Fiat",
    description:
      "Com um plano de revisões, você pode ter descontos e preços fixos. É mais economia para você e garantia do seu FIAT Cronos sempre bem cuidado.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/img-servicos-revisoes.jpg",
  },
];

export default aboutData;
