const highlightData = [
  {
    slug: "destaque-1",
    title: "",
    titleMobile: "",
    description: "",
    label: "",
    tag: "",
    thumb: "novo-fiat-cronos",
    image: "/assets/images/highlight/img-highlight-01.png",
    imageMobile: "/assets/images/highlight/img-highlight-01-mobile.png",
    link: "",
  },
  {
    slug: "destaque-7",
    title: "Câmbio Automático",
    titleMobile: "Câmbio Automático",
    description:
      "O novo câmbio automático CVT de 7 velocidades oferece o máximo de prazer durante a condução. A mudança de velocidade ocorre sem a indesejável sensação de troca de marchas. Além disso, você conta uma maior eficiência, por conta do baixo consumo de combustível.",
    label: "Câmbio <br />Automático",
    tag: "cambio-automatico",
    thumb: "/assets/images/highlight/thumb-highlight-07.jpg",
    image: "/assets/images/highlight/img-highlight-07.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-07-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-2",
    title: "Design",
    titleMobile: "Design",
    description:
      "Um design moderno composto por linhas expressivas que partem da nova grade com dois filetes paralelos, atravessa a carroceria e emolduram as novas rodas de 16” diamantadas.",
    label: "Design",
    tag: "design",
    thumb: "/assets/images/highlight/thumb-highlight-02.jpg",
    image: "/assets/images/highlight/img-highlight-02.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-02-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-3",
    title: "Performance Eficiente",
    titleMobile: "Performance Eficiente",
    description:
      "Mais performance e eficiência para qualquer trajeto. Sinta a experiência de conduzir o motor Firefly1.3 Flex com o novo câmbio automático CVT ou o motor Firefly 1.0 Flex de maior torque da categoria.",
    label: "Performance <br />Eficiente",
    tag: "performance-eficiente",
    thumb: "/assets/images/highlight/thumb-highlight-03.jpg",
    image: "/assets/images/highlight/img-highlight-03.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-03-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-4",
    title: "Muita Conectividade",
    titleMobile: "Muita Conectividade",
    description:
    "O volante com comandos de rádio e telefone permite que você dirija com mais praticidade e de olho no que realmente importa: a estrada.",
    label: "Muita<br /> Conectividade",
    tag: "central-multimidia",
    thumb: "/assets/images/highlight/thumb-highlight-04.jpg",
    image: "/assets/images/highlight/img-highlight-04.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-04-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-5",
    title: "Segurança",
    titleMobile: "Segurança",
    description:
    "Sua proteção é garantida através do Airbag duplo (motorista e passageiro) e os sistemas auxiliares de segurança, como ESS (Sinalização de frenagem de emergência).",
    label: "Segurança",
    tag: "seguranca",
    thumb: "/assets/images/highlight/thumb-highlight-05.jpg",
    image: "/assets/images/highlight/img-highlight-05.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-05-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-6",
    title: "Espaço",
    titleMobile: "Espaço",
    description:
    "Mais espaço pra você e sua família. Experimente a capacidade de 525l no porta-malas e conduza com conforto e amplitude.",
    label: "Espaço",
    tag: "espaco",
    thumb: "/assets/images/highlight/thumb-highlight-06.jpg",
    image: "/assets/images/highlight/img-highlight-06.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-06-mobile.jpg",
    link: "",
  },
];

export default highlightData;
