apiVersion: v2
name: microservice
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 1.0.0
    repository: s3://digitalcode-helm-charts/stable
