const highlightData = [
  {
    slug: "destaque-1",
    title: "",
    titleMobile: "",
    description: "",
    label: "",
    tag: "",
    thumb: "",
    image: "/assets/images/highlight/img-highlight-01.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-01-mobile.jpg",
    link: "",
  },
  // {
  //   slug: "destaque-2",
  //   title: "BEM-VINDO À <br />FABULOSA POTÊNCIA <br />DO FIAT ARGO",
  //   titleMobile: "FABULOSA POTÊNCIA",
  //   description:
  //     "O <strong>novo câmbio automático CVT</strong> proporciona uma condução eficiente e agradável, sem trancos na passagem de marcha e com a opção de trocas sequenciais de 7 velocidades",
  //   label: "Novo <br />câmbio AT",
  //   tag: "novo-cambio-at",
  //   thumb: "/assets/images/highlight/thumb-highlight-02.png",
  //   image: "/assets/images/highlight/img-highlight-02.png",
  //   imageMobile: "/assets/images/highlight/img-highlight-02-mobile.png",
  //   link: "",
  // },
  {
    slug: "destaque-3",
    title: "ELEGÂNCIA EM <br/>CADA DETALHE",
    titleMobile: "ELEGÂNCIA EM CADA DETALHE",
    description:
      "Longe do solo, mais perto da sua próxima aventura. O Fiat Argo está mais <strong>robusto e aventureiro</strong>. Seu design frontal foi atualizado, mas manteve sua identidade como o detalhe da flag italiana e o novo logo Fiat script.",
    label: "Design <br />italiano",
    tag: "design-italiano",
    thumb: "/assets/images/highlight/thumb-highlight-03.jpg",
    image: "/assets/images/highlight/img-highlight-03.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-03-mobile.jpg",
    link: "",
  },  
  {
    slug: "destaque-4",
    title: "CONECTIVIDADE <br/>A TODO MOMENTO",
    titleMobile: "CONECTIVIDADE A TODO MOMENTO",
    description:
      "Com a <strong>Central Multimídia de 7”</strong> do tipo flutuante, você conecta o seu smartphone via Android Auto ou Apple CarPlay e não desvia o olhar de onde mais importa. E é sempre bom lembrar que você pode controlar tudo pelo volante multifuncional.",
    label: "Central <br />Multimidia",
    tag: "central-multimidia",
    thumb: "/assets/images/highlight/thumb-highlight-04.jpg",
    image: "/assets/images/highlight/img-highlight-04.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-04-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-5",
    title: "MAIS <br />MODERNIDADE",
    titleMobile: "MAIS MODERNIDADE",
    description:
      "Seu Argo está sempre de portas abertas para uma nova aventura. Com o sistema <strong>Keyless Entry N’ Go</strong>, você destrava as portas e dá a partida no carro sem tirar as chaves do bolso. É só chegar e dirigir.",
    label: "Keyless <br />Entry N` Go",
    tag: "keyless-entry-n-go",
    thumb: "/assets/images/highlight/thumb-highlight-05.jpg",
    image: "/assets/images/highlight/img-highlight-05.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-05-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-6",
    title: "MAIS <br />VERSATILIDADE",
    titleMobile: "MAIS VERSATILIDADE",
    description:
      "Agilidade dentro e fora da cidade. Os <strong>pneus de uso misto ATR</strong> (todo o terreno), somados ao grande curso de suspensão, deixam o Argo 18 cm de altura longe do solo na versão Trekking, você tem a versatilidade e confiança para desbravar novos terrenos.",
    label: "Pneus de <br />uso misto",
    tag: "pneus-de-uso-misto",
    thumb: "/assets/images/highlight/thumb-highlight-06.jpg",
    image: "/assets/images/highlight/img-highlight-06.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-06-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-7",
    title: "SEGURANÇA <br />REFORÇADA",
    titleMobile: "SEGURANÇA REFORÇADA",
    description:
      "O <strong>Controle de Tração e Estabilidade</strong> do Fiat Argo corrige a rotação das rodas e estabiliza o veículo automaticamente em curvas mais acentuadas. E na hora de sair de ladeiras, você ainda conta com o assistente de partidas Hill Holder. É muita tecnologia.",
    label: "Controle <br />de tração",
    tag: "controle-de-tracao",
    thumb: "/assets/images/highlight/thumb-highlight-07.jpg",
    image: "/assets/images/highlight/img-highlight-07.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-07-mobile.jpg",
    link: "",
  },
  {
    slug: "destaque-8",
    title: "GARANTA <br/>PRATICIDADE",
    titleMobile: "GARANTA PRATICIDADE",
    description:
      "Dentro do Fiat Argo, a previsão é sempre de tempo bom. Com o ar-condicionado digital, você tem mais praticidade para ajustar a temperatura ideal.",
    label: "Ar-condicionado <br />digital",
    tag: "ar-condicionado-digital",
    thumb: "/assets/images/highlight/thumb-highlight-08.jpg",
    image: "/assets/images/highlight/img-highlight-08.jpg",
    imageMobile: "/assets/images/highlight/img-highlight-08-mobile.jpg",
    link: "",
  },
];

export default highlightData;
